[package]
name="hm-channel-slack"
version.workspace=true
edition.workspace=true
license.workspace=true
[dependencies]
hm-core={path="../../hm-core"}
hm-sdk={path="../../hm-sdk"}
hm-auth={path="../../hm-auth"}
anyhow.workspace=true
serde.workspace=true
serde_json.workspace=true
rustls={workspace=true,optional=true}
rustls-webpki={workspace=true,optional=true}
webpki-roots={workspace=true,optional=true}
[features]
tls=["dep:rustls","dep:rustls-webpki","dep:webpki-roots"]
