#!/usr/bin/env python3
"""dump_env_vars.py — docs/env-vars.md aus Code + .env.production.example generieren.

Vorher: kein Dokument listet jede `HM_*`-Variable auf. Wer ein Deployment
aufsetzt, fuehlt entweder die Defaults aus dem Code oder fragt nach.

Nachher: `docs/env-vars.md` (auto-generiert) enthaelt eine Tabelle mit
Name, Default-Wert, Datei:Zeile der ersten Verwendung in produktivem Code
(`crates/`, `scripts/`, `plugins/`, `agents/`, `ghm_core/`, `ui/`),
und ob die Variable in `.env.production.example` dokumentiert ist.

Idempotenz: zweimal laufen ist ein No-Op (Inhalte deterministisch aus
grep-able Quellen). Wird per `make verify` als `validate`-Sub-Target
mitgeprueft.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ENV_EXAMPLE = REPO / ".env.production.example"
DOC_PATH = REPO / "docs" / "env-vars.md"
PROD_DIRS = ["crates", "scripts", "plugins", "agents", "ghm_core", "ui"]

# HM_* var name (uppercase + underscore, 3..40 chars total). Filter
# bare-prefix matches (HM_LLM_) in post-processing.
HM_RE = re.compile(r"\bHM_[A-Z][A-Z0-9_]{2,40}\b")


def _scan_code() -> dict[str, str]:
    """Return {var: first_usage_relpath:lineno}.

    Uses `git grep -nE` (faster than Python rglob, and works on the
    current index). Excludes tests/ and the dump_env_vars.py itself.
    """
    cmd = ["git", "grep", "-nE", r"\bHM_[A-Z][A-Z0-9_]{2,40}\b",
           "--", *PROD_DIRS]
    try:
        out = subprocess.run(cmd, cwd=REPO, capture_output=True,
                            text=True, check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return {}
    first: dict[str, str] = {}
    for line in out.splitlines():
        # Format: "path:lineno:content"
        parts = line.split(":", 2)
        if len(parts) < 3:
            continue
        path, lineno, content = parts
        for m in HM_RE.finditer(content):
            var = m.group(0)
            if var.endswith("_"):  # bare prefix; ignore
                continue
            if var not in first:
                first[var] = f"{path}:{lineno}"
    return first


def _scan_env_example() -> dict[str, str]:
    """Return {var: 'default-value-or-(commented)'}.

    Comprehends both `HM_FOO=value` and commented `# HM_FOO=value` lines.
    """
    out: dict[str, str] = {}
    if not ENV_EXAMPLE.is_file():
        return out
    for line in ENV_EXAMPLE.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\s*#?\s*(HM_[A-Z][A-Z0-9_]*)\s*=\s*(.*?)\s*$", line)
        if not m:
            continue
        var, value = m.group(1), m.group(2)
        if not value or value.startswith("#"):
            value = "(commented out)"
        out[var] = value
    return out


def _render(usages: dict[str, str], documented: dict[str, str]) -> str:
    lines = [
        "# Environment Variables",
        "",
        "Auto-generated by `scripts/dump_env_vars.py`. Do NOT edit by hand — ",
        "rerun the script to refresh.",
        "",
        f"- Total HM_* variables in code: **{len(usages)}**",
        f"- Documented in `.env.production.example`: **{len(documented)}**",
        f"- Undocumented (need attention): **{len(set(usages) - set(documented))}**",
        "",
        "## Katalog",
        "",
        "| Variable | Default in `.env.production.example` | First use in code |",
        "|----------|--------------------------------------|-------------------|",
    ]
    for var in sorted(usages):
        default = documented.get(var, "_(fehlt — bitte ergaenzen)_")
        first_use = usages[var]
        lines.append(f"| `{var}` | `{default}` | `{first_use}` |")
    lines += [
        "",
        "## Konvention",
        "",
        "- `HM_*` ist reservierter Prefix fuer Heavy-Metal-Konfiguration.",
        "- Pflicht-Variablen (z.B. `HM_OWNER_TOKEN`) starten das Gateway NICHT ohne Wert.",
        "- Optionale Variablen werden in `.env.production.example` auskommentiert.",
        "- Tests verwenden bewusst `HM_TESTCHAN_*` / `HM_CORE_NONEXISTENT_VAR__`,",
        "  damit sie nicht mit Produktion interferieren.",
        "",
        "## Regenerieren",
        "",
        "```bash",
        "python3 scripts/dump_env_vars.py",
        "```",
        "",
        "_Dieses Dokument wird durch `scripts/dump_env_vars.py` erzeugt._",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true",
                   help="exit 1 wenn docs/env-vars.md nicht aktuell ist")
    args = p.parse_args(argv)

    usages = _scan_code()
    documented = _scan_env_example()
    body = _render(usages, documented)

    if args.check:
        if not DOC_PATH.is_file():
            print(f"FAIL: {DOC_PATH} fehlt — `python3 scripts/dump_env_vars.py` ausfuehren")
            return 1
        current = DOC_PATH.read_text(encoding="utf-8")
        if current != body:
            print(f"FAIL: {DOC_PATH} ist nicht aktuell — `python3 scripts/dump_env_vars.py` ausfuehren")
            return 1
        print(f"OK: {DOC_PATH} ist aktuell ({len(usages)} vars)")
        return 0

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(body, encoding="utf-8")
    print(f"wrote {DOC_PATH} ({len(body)} bytes, {len(usages)} vars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())